# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.6.0
  - oldrel
  - release
jobs:
  include:
    - r: oldrel
    - r: release
    - r: 3.6.0
      repos:
        CRAN: "https://mran.microsoft.com/snapshot/2019-09-10"
sudo: false
cache: packages
warnings_are_errors: false
r_github_packages:
  - r-lib/pkgdown
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libv8-dev
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
